import { afterEach, describe, expect, test } from 'bun:test'
import { mkdtemp, mkdir, readdir, readFile, rm, symlink, writeFile } from 'node:fs/promises'
import { join, resolve } from 'node:path'
import { tmpdir } from 'node:os'
import { checkProject, freshBuild, freshInit, newDocument, reviewDocument } from '../src/cli/fresh/commands'
import { matches } from '../src/cli/fresh/model'
import { uncoveredSources, whichDocs } from '../src/cli/fresh/query'
import { updateRegion } from '../src/cli/fresh/storage'

const roots: string[] = []
const cli = resolve(import.meta.dir, '../src/cli/index.ts')
afterEach(async () => { for (const root of roots.splice(0)) await rm(root, { recursive: true, force: true }) })
async function fixture(): Promise<string> {
  const root = await mkdtemp(join(tmpdir(), 'dewey-fresh-'))
  roots.push(root)
  await mkdir(join(root, 'src'))
  await writeFile(join(root, 'src/index.ts'), "export const mode = 'safe'\n")
  await writeFile(join(root, 'package.json'), JSON.stringify({ name: 'scratch-widget', description: 'A tiny widget.', scripts: { test: 'echo verified' } }))
  return root
}
async function authored(root: string): Promise<void> {
  await writeFile(join(root, 'docs/src.agent.md'), '---\nkind: map\ntitle: Source map\ncovers: ["src/*"]\n---\n\n# Source map\n\n`src/index.ts` exports the mode.\n\n## Invariants\n\nThe default mode is safe.\n')
  await writeFile(join(root, 'docs/quickstart.md'), '---\nkind: guide\ntitle: Get started\ncovers: []\n---\n\n# Get started\n\nRun `bun run test`. Expect verified.\n\n## Verify\n\nThe test is a smoke check.\n\n[Verification](#verify)\n')
  await reviewDocument('docs/src.agent.md', root)
  await freshBuild(root)
}
async function ready(): Promise<string> { const root = await fixture(); await freshInit({ rules: false }, root); await authored(root); return root }
async function codes(root: string): Promise<string[]> { return (await checkProject(root)).issues.map(issue => issue.code) }
function run(root: string, args: string[]) {
  const result = Bun.spawnSync([process.execPath, cli, ...args], { cwd: root, stdout: 'pipe', stderr: 'pipe' })
  return { code: result.exitCode, out: result.stdout.toString(), err: result.stderr.toString() }
}

describe('fresh-project loop', () => {
  test('actual CLI initializes without TS config, authors, reviews, builds, and checks', async () => {
    const root = await fixture()
    const initialized = run(root, ['init', '--rule', 'Preserve mode semantics.'])
    expect(initialized.code).toBe(0)
    expect(await readFile(join(root, 'AGENTS.md'), 'utf8')).toContain('Preserve mode semantics.')
    expect(await readFile(join(root, '.dewey/site/index.html'), 'utf8')).toContain('Get started')
    expect(await Bun.file(join(root, 'dewey.config.ts')).exists()).toBe(false)
    expect(run(root, ['check', '--json']).code).toBe(1)
    expect(await codes(root)).toContain('DOC_DRAFT')
    await authored(root)
    expect(run(root, ['review', 'docs/src.agent.md']).code).toBe(0)
    expect(run(root, ['build']).code).toBe(0)
    const checked = run(root, ['check', '--json'])
    expect(checked.code).toBe(0)
    expect(JSON.parse(checked.out)).toEqual({ passed: true, issues: [] })
    expect((await readFile(join(root, 'AGENTS.md'), 'utf8')).split('\n').length).toBeLessThanOrEqual(150)
    expect(await readFile(join(root, 'SKILL.md'), 'utf8')).toContain('from another project')
    expect(await readFile(join(root, '.agents/skills/dewey-author/SKILL.md'), 'utf8')).toContain('dewey review')
  })
  test('build publishes the real renderer and keeps code examples intact', async () => {
    const root = await ready()
    await writeFile(join(root, 'README.md'), '# Home\n\nA widget.\n')
    const path = join(root, 'docs/quickstart.md')
    await writeFile(path, (await readFile(path, 'utf8')) + '\n[Home](../README.md)\n\n`[Home](../README.md)`\n\n```md\n[Home](../README.md)\n```\n')
    await freshBuild(root)
    const html = await readFile(join(root, '.dewey/site/docs/quickstart.html'), 'utf8')
    expect(html).toContain('dw-sidebar')
    expect(html).not.toContain('[object Object]')
    expect(html).toContain('href="../readme.html" class="dw-markdown-link"')
    expect(html).toContain('<code class="dw-inline-code">[Home](../README.md)</code>')
    expect(html).toContain('<code class="dw-code-block-code">[Home](../README.md)</code>')
    // The default look is deweydocs.com's: a Docs / page bar, a Copy page menu and a footer line.
    expect(html).toContain('dw-skin-dewey')
    expect(html).toContain('href="../skins/dewey.css"')
    expect(html).not.toContain('themes/ink.css')
    expect(html).toContain('<span class="dw-topbar-current">Get started</span>')
    expect(html).toContain('<div class="dw-sidebar-search"><button type="button" class="dw-cmd-trigger">')
    expect(html).toContain('Copy page for agent')
    expect(html).toContain('<a class="dw-ctx-item" href="../llms.txt">')
    expect(html.match(/data-dw-open="/g)).toHaveLength(2)
    expect(html).toContain('<footer class="dw-site-foot">')
    expect(html).toContain('<a class="dw-powered" href="https://deweydocs.com"')
    // The front page is a card for each listed page, grouped like the sidebar.
    const home = await readFile(join(root, '.dewey/site/index.html'), 'utf8')
    expect(home).toContain('<a class="dw-home-card" href="docs/quickstart.html">')
    expect(home).not.toContain('dw-toc')
    // Pages work without JavaScript and carry only their own doc; one small script adds behavior.
    expect(html).not.toContain('dewey-data')
    expect(html).not.toContain('client.js')
    expect(html).not.toContain('A widget.')
    expect(html).toContain('site.js')
    expect(await Bun.file(join(root, '.dewey/site/client.js')).exists()).toBe(false)
    expect((await readFile(join(root, '.dewey/site/site.js'))).length).toBeLessThan(30_000)
    const search = await readFile(join(root, '.dewey/site/search.js'), 'utf8')
    expect(search).toContain('"t":"Get started"')
    expect(search).toContain('["verify","Verify"]')
    expect(search).not.toContain('.agent')
    expect(await codes(root)).not.toContain('SITE_NAV_MISSING')
  })
  test('plain fences stay blocks, a README without a heading takes the project name, image links get no arrow', async () => {
    const root = await ready()
    await writeFile(join(root, 'README.md'), '[![Logo](docs/logo.svg)](https://example.com)\n\nA widget.\n\n```\nsrc/\n  index.ts   # entry\n```\n')
    await writeFile(join(root, 'docs/logo.svg'), '<svg xmlns="http://www.w3.org/2000/svg"/>\n')
    await freshBuild(root)
    const html = await readFile(join(root, '.dewey/site/readme.html'), 'utf8')
    expect(html).toContain('<code class="dw-code-block-code">src/\n  index.ts   # entry</code>')
    expect(html).toContain('<title>scratch-widget</title>')
    expect(html).not.toContain('dw-markdown-external')
    expect(await Bun.file(join(root, '.dewey/site/assets/docs/logo.svg')).exists()).toBe(true)
  })
  test('README raw HTML renders sanitized with its image, alerts become callouts, a lone README leads Guides', async () => {
    const root = await ready()
    await rm(join(root, 'docs/quickstart.md'))
    await writeFile(join(root, 'README.md'), '<div align="center">\n\n# Widget\n\n<br>\n\n<img src="docs/hero.png" alt="Hero" width="100%">\n\n<script>alert(1)</script>\n\n</div>\n\n> [!NOTE]\n> Early days.\n')
    await writeFile(join(root, 'docs/hero.png'), 'png')
    await freshBuild(root)
    const html = await readFile(join(root, '.dewey/site/readme.html'), 'utf8')
    expect(html).toContain('<div align="center">')
    expect(html).toContain('src="assets/docs/hero.png"')
    expect(html).not.toContain('&lt;br&gt;')
    expect(html).not.toContain('<script>alert')
    expect(html).toContain('dw-markdown-alert-note')
    expect(html).toContain('<p class="dw-markdown-alert-title">Note</p>')
    expect(html).not.toContain('[!NOTE]')
    expect(html).not.toContain('dw-breadcrumbs')
    expect(await Bun.file(join(root, '.dewey/site/assets/docs/hero.png')).exists()).toBe(true)
    const groups = [...html.matchAll(/dw-sidebar-group-title[^>]*><span>([^<]+)/g)].map(match => match[1])
    expect(groups[0]).toBe('Guides')
  })
  test('order and group frontmatter arrange the sidebar', async () => {
    const root = await ready()
    await writeFile(join(root, 'README.md'), '# Home\n\nA widget.\n')
    await writeFile(join(root, 'docs/zeta.md'), '---\nkind: guide\nsummary: Zeta.\norder: 1\ngroup: Recipes\n---\n# Zeta\n\nZeta.\n')
    await writeFile(join(root, 'docs/alpha.md'), '---\nkind: guide\nsummary: Alpha.\norder: 2\ngroup: Recipes\n---\n# Alpha\n\nAlpha.\n')
    await freshBuild(root)
    const html = await readFile(join(root, '.dewey/site/index.html'), 'utf8')
    const groups = [...html.matchAll(/dw-sidebar-group-title[^>]*><span>([^<]+)/g)].map(match => match[1])
    expect(groups).toEqual(['Start here', 'Recipes'])
    expect(html.indexOf('>Zeta<')).toBeLessThan(html.indexOf('>Alpha<'))
    await writeFile(join(root, 'docs/alpha.md'), '---\nkind: guide\nsummary: Alpha.\norder: first\n---\n# Alpha\n\nAlpha.\n')
    expect(await codes(root)).toContain('DOC_META')
  })
  test('issues name the file line and a fix', async () => {
    const root = await ready()
    // quickstart.md has 6 frontmatter lines and a blank line, so body line 3 is file line 9.
    const path = join(root, 'docs/quickstart.md')
    const original = await readFile(path, 'utf8')
    await writeFile(path, original.replace('Run `bun run test`.', 'Run `bun run absent`.') + '\n```sh\nbun run test\ndewey_nonexistent_command_87\n```\n')
    const { issues } = await checkProject(root)
    const script = issues.find(issue => issue.code === 'MISSING_SCRIPT')!
    expect(script.line).toBe(original.split('\n').findIndex(line => line.includes('bun run test')) + 1)
    expect(script.fix).toContain('package.json')
    const command = issues.find(issue => issue.code === 'UNKNOWN_COMMAND')!
    expect(command.line).toBe(original.split('\n').length + 3)
    const text = run(root, ['check'])
    expect(text.out).toContain(`docs/quickstart.md:${script.line} MISSING_SCRIPT`)
    expect(text.out).toContain('  fix: ')
    expect(issues.every(issue => issue.fix)).toBe(true)
  })
  test('which and uncovered route by code', async () => {
    const root = await ready()
    const which = await whichDocs('src/index.ts', root)
    expect(which.docs.map(doc => [doc.path, doc.kind, doc.pattern])).toEqual([['docs/src.agent.md', 'map', 'src/*']])
    expect(which.docs[0].tokens).toBeGreaterThan(0)
    expect((await whichDocs('src', root)).docs.map(doc => doc.path)).toEqual(['docs/src.agent.md'])
    expect((await whichDocs('package.json', root)).docs).toEqual([])
    await expect(whichDocs('../elsewhere.ts', root)).rejects.toThrow('outside the project')
    expect((await uncoveredSources(root)).areas).toEqual([])
    await mkdir(join(root, 'src/sync'))
    await writeFile(join(root, 'src/sync/index.ts'), 'export {}\n')
    expect((await uncoveredSources(root)).areas).toEqual([{ area: 'src/sync', files: ['src/sync/index.ts'] }])
    const cli = run(root, ['which', 'src/index.ts', '--json'])
    expect(JSON.parse(cli.out).docs[0].path).toBe('docs/src.agent.md')
    expect(run(root, ['uncovered']).out).toContain('dewey new map src/sync')
  })
  test('published packages must ship the docs downstream agents read', async () => {
    const root = await ready()
    const pkgPath = join(root, 'package.json')
    const pkg = JSON.parse(await readFile(pkgPath, 'utf8'))
    await writeFile(pkgPath, JSON.stringify({ ...pkg, files: ['dist'] }))
    const missing = (await checkProject(root)).issues.find(issue => issue.code === 'PUBLISH_MISSING')!
    expect(missing.message).toContain('AGENTS.md, SKILL.md, docs/quickstart.md')
    await writeFile(pkgPath, JSON.stringify({ ...pkg, files: ['dist', 'docs/', 'AGENTS.md', 'SKILL.md', '!docs/quickstart.md'] }))
    expect((await checkProject(root)).issues.find(issue => issue.code === 'PUBLISH_MISSING')?.message).toContain('docs/quickstart.md')
    await writeFile(pkgPath, JSON.stringify({ ...pkg, files: ['dist', 'docs', '*.md'] }))
    expect(await codes(root)).not.toContain('PUBLISH_MISSING')
    await writeFile(pkgPath, JSON.stringify(pkg))
    await writeFile(join(root, '.npmignore'), 'docs/\n')
    expect(await codes(root)).toContain('PUBLISH_MISSING')
    await writeFile(pkgPath, JSON.stringify({ ...pkg, private: true }))
    expect(await codes(root)).not.toContain('PUBLISH_MISSING')
  })
  test('build publishes .md copies, llms-full.txt and sized indexes', async () => {
    const root = await ready()
    await writeFile(join(root, 'README.md'), '# Home\n\nA widget. See [Get started](docs/quickstart.md).\n')
    await writeFile(join(root, 'docs/history.md'), '---\nkind: history\n---\n\n# Old plan\n\nSecret history.\n')
    await freshBuild(root)
    const site = join(root, '.dewey/site')
    expect(await readFile(join(site, 'readme.md'), 'utf8')).toContain('[Get started](docs/quickstart.md)')
    expect(await readFile(join(site, 'docs/quickstart.md'), 'utf8')).toContain('Run `bun run test`.')
    const index = await readFile(join(site, 'llms.txt'), 'utf8')
    expect(index).toMatch(/- \[Get started\]\(docs\/quickstart\.md\): Run bun run test\. Expect verified\. \(\d+ lines, ~\d+ tokens\)/)
    expect(index).toContain('[llms-full.txt](llms-full.txt)')
    const full = await readFile(join(site, 'llms-full.txt'), 'utf8')
    expect(full).toContain('<!-- docs/quickstart.md -->')
    expect(full).toContain('A widget.')
    expect(full).not.toContain('Secret history')
    expect(full).not.toContain('Source map')
    const repo = await readFile(join(root, 'llms.txt'), 'utf8')
    expect(repo).toContain('[Get started](docs/quickstart.md)')
    expect(repo).toContain('[Home](README.md)')
    expect(repo).not.toContain('.html')
    expect(await codes(root)).toEqual([])
  })
  test('dewey new scaffolds each kind and refuses to overwrite', async () => {
    const root = await ready()
    await mkdir(join(root, 'src/sync'))
    await writeFile(join(root, 'src/sync/index.ts'), 'export {}\n')
    expect(await newDocument('map', 'src/sync', root)).toBe('docs/src-sync.agent.md')
    const map = await readFile(join(root, 'docs/src-sync.agent.md'), 'utf8')
    expect(map).toContain('covers: ["src/sync/*"]')
    expect(map).toContain('- `src/sync/index.ts`')
    expect(await codes(root)).not.toContain('MAP_MISSING')
    expect(await newDocument('guide', 'Deploy to staging', root)).toBe('docs/deploy-to-staging.md')
    expect(await readFile(join(root, 'docs/deploy-to-staging.md'), 'utf8')).toContain('## Check it worked')
    expect(await newDocument('reference', 'CLI flags', root)).toBe('docs/reference/cli-flags.md')
    expect(await newDocument('history', 'Why JSONL', root)).toMatch(/^docs\/history\/\d{4}-\d{2}-\d{2}-why-jsonl\.md$/)
    await expect(newDocument('guide', 'Deploy to staging', root)).rejects.toThrow('already exists')
    await expect(newDocument('map', 'src/nowhere', root)).rejects.toThrow('No source files')
    await expect(newDocument('concept', 'x', root)).rejects.toThrow('Unknown kind')
    expect(run(root, ['new', 'guide', 'Rotate keys']).out).toContain('Created docs/rotate-keys.md')
    const issues = await codes(root)
    expect(issues).toContain('DOC_DRAFT')
    expect(issues).not.toContain('DOC_KIND')
  })
  test('host pointer files are opt-in and must redirect to the front door', async () => {
    const root = await fixture()
    expect(run(root, ['init', '--no-rules', '--host', 'TOOL.md']).code).toBe(0)
    expect(await readFile(join(root, 'TOOL.md'), 'utf8')).toContain('AGENTS.md')
    await authored(root)
    expect(await codes(root)).toEqual([])
    await writeFile(join(root, 'TOOL.md'), 'Local notes only.\n')
    expect(await codes(root)).toContain('FRONT_DOOR_POINTER')
  })
  test('asks only for missing purpose/rules and makes no partial writes on missing input', async () => {
    const root = await fixture()
    await writeFile(join(root, 'package.json'), '{"name":"empty"}')
    expect(run(root, ['init', '--no-rules']).code).toBe(1)
    expect(await Bun.file(join(root, '.dewey/project.json')).exists()).toBe(false)
    expect(run(root, ['init', '--purpose', 'Test a tool.', '--no-rules']).code).toBe(0)
  })
  test('source additions require maps and source edits require explicit review, never just build', async () => {
    const root = await ready()
    await mkdir(join(root, 'src/sync'))
    await writeFile(join(root, 'src/sync/index.ts'), 'export const sync = true\n')
    expect(await codes(root)).toContain('MAP_MISSING')
    await writeFile(join(root, 'docs/sync.agent.md'), '---\nkind: map\ncovers: ["src/sync/**"]\n---\n# Sync map\n\n`src/sync/index.ts` declares sync.\n')
    await reviewDocument('docs/sync.agent.md', root)
    await freshBuild(root)
    expect(await codes(root)).toEqual([])
    await writeFile(join(root, 'src/index.ts'), "export const mode = 'fast'\n")
    await freshBuild(root)
    expect(await codes(root)).toContain('REVIEW_REQUIRED')
    await writeFile(join(root, 'docs/src.agent.md'), (await readFile(join(root, 'docs/src.agent.md'), 'utf8')).replace('default mode is safe', 'default mode is fast'))
    expect(await codes(root)).toContain('REVIEW_REQUIRED')
    await reviewDocument('docs/src.agent.md', root)
    await freshBuild(root)
    expect(await codes(root)).toEqual([])
  })
  test('catches missing paths/scripts/commands, bad links and anchors, then recovers', async () => {
    const root = await ready()
    const path = join(root, 'docs/quickstart.md')
    const original = await readFile(path, 'utf8')
    for (const [text, code] of [
      ['`src/missing.ts`', 'MISSING_PATH'], ['`bun run absent`', 'MISSING_SCRIPT'],
      ['```sh\ndewey_nonexistent_command_87\n```', 'UNKNOWN_COMMAND'],
      ['[Missing](missing.md)', 'BROKEN_LINK'], ['[Missing](#absent)', 'BROKEN_ANCHOR'],
    ]) {
      await writeFile(path, original + '\n' + text + '\n')
      expect(await codes(root)).toContain(code)
      expect(run(root, ['check', '--json']).code).toBe(1)
      await writeFile(path, original)
      expect(await codes(root)).toEqual([])
    }
    // Flags on a continuation line are not commands; the next line after it is checked again.
    await writeFile(path, original + '\n```sh\nbun run test \\\n  --watch \\\n  --bail\ndewey_nonexistent_command_87\n```\n')
    expect((await checkProject(root)).issues.filter(issue => issue.code === 'UNKNOWN_COMMAND').map(issue => issue.message)).toEqual(['Not a package bin, script runner or allowed command: dewey_nonexistent_command_87'])
    await writeFile(path, original)
  })
  test('checks front-door budget, generated freshness, actual navigation and rendered links', async () => {
    const root = await ready()
    const front = join(root, 'AGENTS.md'); const original = await readFile(front, 'utf8')
    await writeFile(front, original + '\nAnother rule\n'.repeat(150))
    expect(await codes(root)).toContain('FRONT_DOOR_BUDGET')
    await writeFile(front, original)
    const guide = join(root, 'docs/quickstart.md')
    await writeFile(guide, await readFile(guide, 'utf8') + '\nA new verified step.\n')
    expect(await codes(root)).toContain('STALE_OUTPUT')
    await freshBuild(root)
    const home = join(root, '.dewey/site/index.html'); const homeText = await readFile(home, 'utf8')
    await writeFile(home, homeText.replace(/<nav class="dw-sidebar-nav">[\s\S]*?<\/nav>/, '<nav class="dw-sidebar-nav"><a href="absent.html">Broken</a></nav>'))
    expect(await codes(root)).toContain('NAV_MISSING')
    expect(await codes(root)).toContain('SITE_LINK')
    await expect(freshBuild(root)).rejects.toThrow('modified or unowned')
    await writeFile(home, homeText)
    expect(await codes(root)).toEqual([])
  })
  test('manual regions survive reruns; maps/history stay out; generated stale pages are pruned', async () => {
    const root = await ready()
    const front = join(root, 'AGENTS.md'); const manual = '\n## Manual rule\n\nNever delete local state.\n'
    await writeFile(front, await readFile(front, 'utf8') + manual)
    await writeFile(join(root, 'llms.txt'), 'Manual preface.\n' + await readFile(join(root, 'llms.txt'), 'utf8') + 'Manual footer.\n')
    await writeFile(join(root, 'docs/old-plan.md'), '---\nkind: history\n---\n# OLD HISTORY SECRET\n')
    await freshInit({ rules: false }, root)
    expect((await readFile(front, 'utf8')).endsWith(manual)).toBe(true)
    expect(await readFile(join(root, 'llms.txt'), 'utf8')).toStartWith('Manual preface.')
    expect(await readFile(join(root, 'llms.txt'), 'utf8')).toEndWith('Manual footer.\n')
    const home = await readFile(join(root, '.dewey/site/index.html'), 'utf8')
    expect(home).not.toContain('OLD HISTORY SECRET')
    expect(home).not.toContain('Source map')
    expect(await Bun.file(join(root, '.dewey/site/docs/old-plan.html')).exists()).toBe(false)
    await writeFile(join(root, 'docs/extra.md'), '---\nkind: reference\ncovers: []\nnav: false\n---\n# Extra reference\n')
    await freshBuild(root)
    expect(await codes(root)).toEqual([])
    expect(await Bun.file(join(root, '.dewey/site/docs/extra.html')).exists()).toBe(true)
    await rm(join(root, 'docs/extra.md'))
    expect(await codes(root)).toContain('STALE_OUTPUT')
    await freshBuild(root)
    expect(await Bun.file(join(root, '.dewey/site/docs/extra.html')).exists()).toBe(false)
  })
  test('README, nested relative links, references and assets share the rendered model', async () => {
    const root = await ready()
    await mkdir(join(root, 'docs/reference'))
    await writeFile(join(root, 'README.md'), '# Project overview\n\n[Start](docs/quickstart.md#verify)\n')
    await writeFile(join(root, 'docs/reference/api.md'), '---\nkind: reference\nnav: false\ncovers: []\n---\n# API\n\n[Start][guide]\n\n[guide]: ../quickstart.md#verify\n')
    await writeFile(join(root, 'docs/sample.txt'), 'plain text sample\n')
    const guide = join(root, 'docs/quickstart.md')
    await writeFile(guide, await readFile(guide, 'utf8') + '\n[Sample](sample.txt) and [API](reference/api.md)\n')
    await freshBuild(root)
    expect(await codes(root)).toEqual([])
    expect(await readFile(join(root, '.dewey/site/assets/docs/sample.txt'), 'utf8')).toBe('plain text sample\n')
    const original = await readFile(join(root, '.dewey/site/index.html'), 'utf8')
    await writeFile(join(root, 'llms.txt'), 'Unmarked authored content\n')
    await expect(freshBuild(root)).rejects.toThrow('unmarked')
    expect(await readFile(join(root, '.dewey/site/index.html'), 'utf8')).toBe(original)
    expect(await readFile(join(root, 'llms.txt'), 'utf8')).toBe('Unmarked authored content\n')
  })
  test('invalid state and metadata yield structured failures without executing config', async () => {
    const root = await ready()
    await writeFile(join(root, 'dewey.config.ts'), 'throw new Error("must not execute")')
    const notExecuted = run(root, ['check', '--json'])
    expect(notExecuted.err).not.toContain('must not execute')
    expect(JSON.parse(notExecuted.out).issues.map((issue: { code: string }) => issue.code)).toContain('MAP_MISSING')
    await writeFile(join(root, 'docs/bad.md'), '---\nkind: unknown\ncovers: []\n---\n# Invalid\n')
    expect(await codes(root)).toContain('DOC_KIND')
    await writeFile(join(root, '.dewey/project.json'), '{}')
    const result = run(root, ['check', '--json'])
    expect(result.code).toBe(1)
    expect(JSON.parse(result.out).issues[0].code).toBe('PROJECT_INVALID')
  })
  test('init adopts existing docs and keeps authored text', async () => {
    const root = await fixture()
    await writeFile(join(root, 'AGENTS.md'), '# Widget\n\nNever ship on Fridays.\n')
    await writeFile(join(root, 'llms.txt'), '# Widget\n\n> Hand written.\n')
    await mkdir(join(root, 'docs/reference'), { recursive: true })
    await mkdir(join(root, 'docs/plans'), { recursive: true })
    await writeFile(join(root, 'docs/install.md'), '# Install\n\nRun `bun run test`.\n')
    await writeFile(join(root, 'docs/reference/options.md'), '---\ntitle: Options\n---\n\n# Options\n\nNone yet.\n')
    await writeFile(join(root, 'docs/plans/v2.md'), '# The v2 plan\n\nLater.\n')
    await writeFile(join(root, 'docs/source.md'), '---\nkind: map\ntitle: Source\ncovers: ["src/*"]\n---\n\n# Source\n\n`src/index.ts` exports the mode.\n')
    await writeFile(join(root, 'docs/quickstart.md'), '---\nkind: guide\ntitle: Start\n---\n\n# Start\n\nRun `bun run test`.\n')
    await freshInit({ rules: false }, root)
    const front = await readFile(join(root, 'AGENTS.md'), 'utf8')
    expect(front.startsWith('# Widget\n\nNever ship on Fridays.\n')).toBe(true)
    expect(front).toContain('<!-- dewey:begin observed -->')
    const llms = await readFile(join(root, 'llms.txt'), 'utf8')
    expect(llms).toStartWith('# Widget\n\n> Hand written.\n')
    expect(llms).toContain('[Install](docs/install.md)')
    expect(await readFile(join(root, 'docs/install.md'), 'utf8')).toBe('---\nkind: guide\n---\n\n# Install\n\nRun `bun run test`.\n')
    expect(await readFile(join(root, 'docs/reference/options.md'), 'utf8')).toStartWith('---\nkind: reference\ntitle: Options\n')
    expect(await readFile(join(root, 'docs/plans/v2.md'), 'utf8')).toStartWith('---\nkind: history\n')
    expect(await readFile(join(root, 'docs/quickstart.md'), 'utf8')).toContain('title: Start')
    // src/ already has a map, so init does not draft another.
    expect(await Bun.file(join(root, 'docs/src.agent.md')).exists()).toBe(false)
    expect(await Bun.file(join(root, '.dewey/site/docs/install.html')).exists()).toBe(true)
    expect(await Bun.file(join(root, '.dewey/site/docs/plans/v2.html')).exists()).toBe(false)
  })
  test('init that fails leaves the project as it was', async () => {
    const root = await fixture()
    await writeFile(join(root, 'AGENTS.md'), '# Widget\n')
    await writeFile(join(root, 'llms.txt'), '# Widget\n')
    await mkdir(join(root, 'docs'))
    await writeFile(join(root, 'docs/install.md'), '# Install\n')
    await writeFile(join(root, 'docs/broken.md'), '---\nkind: guide\nstatus: someday\n---\n\n# Broken\n')
    await expect(freshInit({ rules: false }, root)).rejects.toThrow('dewey init made no changes')
    expect(await readFile(join(root, 'AGENTS.md'), 'utf8')).toBe('# Widget\n')
    expect(await readFile(join(root, 'docs/install.md'), 'utf8')).toBe('# Install\n')
    expect(await readFile(join(root, 'llms.txt'), 'utf8')).toBe('# Widget\n')
    expect((await readdir(root)).sort()).toEqual(['AGENTS.md', 'docs', 'llms.txt', 'package.json', 'src'])
    expect((await readdir(join(root, 'docs'))).sort()).toEqual(['broken.md', 'install.md'])
  })
  test('refuses existing authored targets and symlink writes; validates metadata and coverage globs', async () => {
    const root = await fixture()
    await writeFile(join(root, 'llms.txt'), '<!-- dewey:begin index -->\n# Hand authored\n')
    await expect(freshInit({ rules: false }, root)).rejects.toThrow('llms.txt has an incomplete or repeated index region')
    expect(await Bun.file(join(root, '.dewey/project.json')).exists()).toBe(false)
    await rm(join(root, 'llms.txt'))
    await symlink(join(root, 'src'), join(root, '.dewey'))
    await expect(freshInit({ rules: false }, root)).rejects.toThrow('symlink')
    expect(matches('src/a.ts', 'src/*')).toBe(true)
    expect(matches('src/sync/a.ts', 'src/*')).toBe(false)
    expect(matches('src/sync/a.ts', 'src/**')).toBe(true)
    expect(() => matches('src/a.ts', '../**')).toThrow('Unsafe')
    expect(() => updateRegion('unmarked notes', 'observed', 'replacement')).toThrow('unmarked')
  })
  test('status, applies and supersedes shape what is published and indexed', async () => {
    const root = await ready()
    await writeFile(join(root, 'docs/old.md'), '---\nkind: guide\ntitle: Old setup\ncovers: []\nsuperseded_by: docs/quickstart.md\n---\n\n# Old setup\n\nThe previous flow.\n')
    await writeFile(join(root, 'docs/plan.md'), '---\nkind: guide\ntitle: Sync plan\ncovers: []\nstatus: proposal\napplies: [web, ios]\n---\n\n# Sync plan\n\nPlanned sync.\n')
    await writeFile(join(root, 'docs/dropped.md'), '---\nkind: guide\ntitle: Dropped idea\ncovers: []\nstatus: abandoned\n---\n\n# Dropped idea\n\nNot pursued.\n')
    await freshBuild(root)
    const site = join(root, '.dewey/site')
    const index = await readFile(join(site, 'llms.txt'), 'utf8')
    expect(index).toContain('[proposal] ')
    expect(index).toContain('applies to web, ios')
    expect(index).not.toContain('Old setup')
    expect(index).not.toContain('Dropped idea')
    const full = await readFile(join(site, 'llms-full.txt'), 'utf8')
    expect(full).not.toContain('Planned sync.')
    expect(full).not.toContain('The previous flow.')
    expect(await readFile(join(site, 'docs/plan.md'), 'utf8')).toContain('**Proposal.**')
    expect(await readFile(join(site, 'docs/old.md'), 'utf8')).toContain('**Replaced** by [Get started](quickstart.md)')
    expect(await Bun.file(join(site, 'docs/dropped.html')).exists()).toBe(false)
    expect(await codes(root)).toEqual([])
    await writeFile(join(root, 'docs/old.md'), '---\nkind: guide\ntitle: Old setup\ncovers: []\nsuperseded_by: docs/gone.md\n---\n\n# Old setup\n')
    await writeFile(join(root, 'docs/plan.md'), '---\nkind: guide\ntitle: Sync plan\ncovers: []\nstatus: maybe\n---\n\n# Sync plan\n')
    const issues = (await checkProject(root)).issues
    expect(issues.find(issue => issue.code === 'SUPERSEDES_MISSING')?.line).toBe(5)
    expect(issues.find(issue => issue.code === 'DOC_STATUS')?.line).toBe(5)
  })
  test('the front-door budget counts host files and tokens', async () => {
    const root = await ready()
    await writeFile(join(root, '.dewey/project.json'), JSON.stringify({ ...JSON.parse(await readFile(join(root, '.dewey/project.json'), 'utf8')), hosts: ['TOOL.md'] }))
    await writeFile(join(root, 'TOOL.md'), 'Read AGENTS.md.\n')
    expect(await codes(root)).toEqual([])
    await writeFile(join(root, 'TOOL.md'), 'Read AGENTS.md. ' + 'word '.repeat(2000) + '\n')
    const issue = (await checkProject(root)).issues.find(item => item.code === 'FRONT_DOOR_BUDGET')
    expect(issue?.message).toContain('TOOL.md: 1 lines')
    expect(issue?.line).toBeUndefined()
  })
  test('a skin styles the site like its project docs and rejects unknown names', async () => {
    const root = await ready()
    const state = join(root, '.dewey/project.json')
    const project = JSON.parse(await readFile(state, 'utf8'))
    const path = join(root, 'docs/quickstart.md')
    await writeFile(path, (await readFile(path, 'utf8')).replace('title: Get started\n', 'title: Get started\ndescription: Run the widget once.\n') + '\n```sh\n# install\nbun install \\\n  --frozen\n```\n')
    await writeFile(state, JSON.stringify({ ...project, skin: 'lattices' }))
    await freshBuild(root)
    const html = await readFile(join(root, '.dewey/site/docs/quickstart.html'), 'utf8')
    expect(html).toContain('dw-skin-lattices')
    expect(html).toContain('href="../skins/lattices.css"')
    expect(html).not.toContain('themes/ink.css')
    expect(html).not.toContain('dw-fresh-theme')
    expect(html).toContain('<header class="dw-page-head"><p class="dw-page-path">/docs/quickstart</p>')
    expect(html).toContain('<p class="dw-page-description">Run the widget once.</p>')
    expect(html).toContain('data-line="comment"')
    expect(html).toContain('data-line="command"')
    expect(html).toContain('data-line="continued"')
    expect(await Bun.file(join(root, '.dewey/site/skins/lattices.css')).exists()).toBe(true)
    expect(await codes(root)).toEqual([])
    await writeFile(state, JSON.stringify({ ...project, skin: 'nope' }))
    const failed = run(root, ['build'])
    expect(failed.code).toBe(1)
    expect(failed.err + failed.out).toContain('skin must be one of dewey, openscout, talkie, lattices, hudsonkit, ink')
    // ink is the plain look with the color theme menu.
    await writeFile(state, JSON.stringify({ ...project, skin: 'ink' }))
    await freshBuild(root)
    const ink = await readFile(join(root, '.dewey/site/docs/quickstart.html'), 'utf8')
    expect(ink).toContain('themes/ink.css')
    expect(ink).not.toContain('dw-skin-')
    expect(ink).not.toContain('dw-topbar-crumbs')
  })
  test('agents get a prompt button, agent paths in the sidebar and nav.json', async () => {
    const root = await ready()
    const state = join(root, '.dewey/project.json')
    const project = JSON.parse(await readFile(state, 'utf8'))
    await freshBuild(root)
    const plain = await readFile(join(root, '.dewey/site/docs/quickstart.html'), 'utf8')
    expect(plain).toContain('<p class="dw-agent-paths-title">Agent files</p>')
    expect(plain).toContain('href="../llms.txt"')
    expect(plain).toContain('href="../nav.json"')
    expect(plain).toContain('<a class="dw-agent-path" href="quickstart.md">this page.md</a>')
    const nav = JSON.parse(await readFile(join(root, '.dewey/site/nav.json'), 'utf8'))
    expect(nav.entrypoints).toEqual({ llms: 'llms.txt', llmsFull: 'llms-full.txt', nav: 'nav.json' })
    expect(nav.groups.flatMap((group: { items: Array<{ url: string; markdown: string }> }) => group.items)).toContainEqual(expect.objectContaining({ url: 'docs/quickstart.html', markdown: 'docs/quickstart.md', source: 'docs/quickstart.md' }))
    await writeFile(state, JSON.stringify({ ...project, skin: 'openscout' }))
    await freshBuild(root)
    const skinned = await readFile(join(root, '.dewey/site/docs/quickstart.html'), 'utf8')
    expect(skinned).toContain('data-dw-copy-prompt="quickstart.md"')
    expect(skinned).toContain(`data-dw-prompt-head="You are working with ${project.name} documentation.`)
    expect(skinned).toContain('<p class="dw-agent-paths-title">Agent paths</p>')
    await writeFile(state, JSON.stringify({ ...project, skin: 'lattices' }))
    await freshBuild(root)
    expect(await readFile(join(root, '.dewey/site/docs/quickstart.html'), 'utf8')).not.toContain('dw-agent-paths')
    expect(await codes(root)).toEqual([])
  })
  test('build keeps the observed region current; check rejects overlap, broad coverage and names moved files', async () => {
    const root = await ready()
    const agents = join(root, 'AGENTS.md')
    const authoredLine = '\nKeep this authored line.\n'
    await writeFile(agents, (await readFile(agents, 'utf8')) + authoredLine)
    await writeFile(join(root, 'package.json'), JSON.stringify({ name: 'scratch-widget', description: 'A tiny widget.', scripts: { test: 'echo verified', lint: 'echo clean' } }))
    expect(await codes(root)).toContain('REGION_STALE')
    await freshBuild(root)
    const front = await readFile(agents, 'utf8')
    expect(front).toContain('`bun run lint`')
    expect(front).toContain(authoredLine)
    expect(await codes(root)).toEqual([])
    await writeFile(join(root, 'docs/wide.agent.md'), '---\nkind: map\ntitle: Everything\ncovers: ["**/*.ts"]\n---\n\n# Everything\n\nAll code.\n')
    const issues = (await checkProject(root)).issues
    expect(issues.find(issue => issue.code === 'COVERAGE_OVERLAP')?.message).toContain('src/index.ts')
    expect(issues.find(issue => issue.code === 'COVERAGE_BROAD')?.line).toBe(4)
    await rm(join(root, 'docs/wide.agent.md'))
    await writeFile(join(root, 'src/index.ts'), "export const mode = 'fast'\n")
    await writeFile(join(root, 'src/extra.ts'), 'export {}\n')
    const review = (await checkProject(root)).issues.find(issue => issue.code === 'REVIEW_REQUIRED')
    expect(review?.message).toContain('changed: src/index.ts')
    expect(review?.message).toContain('added: src/extra.ts')
    await writeFile(agents, front + '\n<!-- dewey:begin observed -->\n')
    expect(await codes(root)).toContain('REGION_INVALID')
  })
  test('commands resolve from package bins, the allowlist and project commands, never PATH', async () => {
    const root = await ready()
    const path = join(root, 'docs/quickstart.md')
    const original = await readFile(path, 'utf8')
    await writeFile(join(root, 'package.json'), JSON.stringify({ name: '@scope/scratch-widget', description: 'A tiny widget.', bin: 'src/index.ts', scripts: { test: 'echo verified' } }))
    await writeFile(path, original + '\n```sh\nscratch-widget --help\nDEBUG=1 bun run test\n# a comment\n```\n\n```sh ignore\nmystery-tool\n```\n')
    expect(await codes(root)).not.toContain('UNKNOWN_COMMAND')
    await writeFile(path, original + '\n```sh\nmystery-tool --run\n```\n')
    expect(await codes(root)).toContain('UNKNOWN_COMMAND')
    const state = join(root, '.dewey/project.json')
    await writeFile(state, JSON.stringify({ ...JSON.parse(await readFile(state, 'utf8')), commands: ['mystery-tool'] }))
    expect(await codes(root)).not.toContain('UNKNOWN_COMMAND')
  })
  test('path#symbol citations must name a declaration, following export *', async () => {
    const root = await ready()
    await writeFile(join(root, 'src/shapes.ts'), "export interface Shape { sides: number }\nexport class Square { area() { return 1 } }\nexport enum Mode { Safe }\nconst hidden = 1\nexport { hidden as visible }\n")
    await writeFile(join(root, 'src/barrel.ts'), "export * from './shapes'\n")
    const path = join(root, 'docs/src.agent.md')
    const original = await readFile(path, 'utf8')
    await writeFile(path, original + '\n`src/index.ts#mode`, `src/shapes.ts#Shape.sides`, `src/shapes.ts#Square.area`, `src/shapes.ts#Mode.Safe`, `src/shapes.ts#visible`, `src/barrel.ts#Square` and [the shape](../src/shapes.ts#Shape).\n')
    expect(await codes(root)).not.toContain('MISSING_SYMBOL')
    await writeFile(path, original + '\n`src/index.ts#mode`\n\n`src/barrel.ts#Circle`\n\n[gone](../src/shapes.ts#Triangle)\n\n`src/nope.ts#x`\n')
    const issues = (await checkProject(root)).issues
    expect(issues.filter(issue => issue.code === 'MISSING_SYMBOL').map(issue => issue.message).sort()).toEqual(['src/barrel.ts does not declare Circle', 'src/shapes.ts does not declare Triangle'])
    expect(issues.find(issue => issue.code === 'MISSING_PATH')?.message).toContain('src/nope.ts')
  })
})
