import chalk from 'chalk'
import { readdir, readFile, writeFile, access } from 'fs/promises'
import { join } from 'path'
import matter from 'gray-matter'
import { loadConfig } from '../config.js'

interface GenerateOptions {
  output?: string
  agentsMd?: boolean
  llmsTxt?: boolean
  docsJson?: boolean
}

interface DocSection {
  id: string
  title: string
  description?: string
  content: string
  order: number
}

async function fileExists(path: string): Promise<boolean> {
  try {
    await access(path)
    return true
  } catch {
    return false
  }
}

async function loadDocs(docsPath: string, sections: string[]): Promise<DocSection[]> {
  const docs: DocSection[] = []

  for (const section of sections) {
    const filePath = join(docsPath, `${section}.md`)
    if (!await fileExists(filePath)) continue

    const content = await readFile(filePath, 'utf-8')
    const { data: frontmatter, content: body } = matter(content)

    docs.push({
      id: section,
      title: (frontmatter.title as string) || section.charAt(0).toUpperCase() + section.slice(1),
      description: frontmatter.description as string | undefined,
      content: body.trim(),
      order: (frontmatter.order as number) || 999,
    })
  }

  // Sort by order
  docs.sort((a, b) => a.order - b.order)

  return docs
}

function generateAgentsMd(projectName: string, tagline: string | undefined, config: Awaited<ReturnType<typeof loadConfig>>, docs: DocSection[]): string {
  if (!config) return ''

  const lines: string[] = []

  // Header
  lines.push(`# ${projectName}`)
  lines.push('')
  if (tagline) {
    lines.push(`> ${tagline}`)
    lines.push('')
  }

  // Critical context
  if (config.agent.criticalContext.length > 0) {
    lines.push('## Critical Context')
    lines.push('')
    lines.push('**IMPORTANT:** Read these rules before making any changes:')
    lines.push('')
    for (const rule of config.agent.criticalContext) {
      lines.push(`- ${rule}`)
    }
    lines.push('')
  }

  // Project structure / entry points
  if (Object.keys(config.agent.entryPoints).length > 0) {
    lines.push('## Project Structure')
    lines.push('')
    lines.push('| Component | Path | Purpose |')
    lines.push('|-----------|------|---------|')
    for (const [name, path] of Object.entries(config.agent.entryPoints)) {
      const displayName = name.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ')
      lines.push(`| ${displayName} | \`${path}\` | |`)
    }
    lines.push('')
  }

  // Navigation rules
  if (config.agent.rules.length > 0) {
    lines.push('## Quick Navigation')
    lines.push('')
    for (const rule of config.agent.rules) {
      lines.push(`- Working with **${rule.pattern}**? → ${rule.instruction}`)
    }
    lines.push('')
  }

  // Documentation sections
  for (const doc of docs) {
    lines.push(`## ${doc.title}`)
    lines.push('')
    if (doc.description) {
      lines.push(`> ${doc.description}`)
      lines.push('')
    }
    lines.push(doc.content)
    lines.push('')
  }

  // Footer
  lines.push('---')
  lines.push(`Generated by [Dewey](https://github.com/arach/dewey) | Last updated: ${new Date().toISOString().split('T')[0]}`)

  return lines.join('\n')
}

function generateLlmsTxt(projectName: string, tagline: string | undefined, docs: DocSection[]): string {
  const lines: string[] = []

  lines.push(`# ${projectName}`)
  lines.push('')
  if (tagline) {
    lines.push(`> ${tagline}`)
    lines.push('')
  }

  lines.push('## Documentation')
  lines.push('')
  for (const doc of docs) {
    lines.push(`- ${doc.title}: /docs/${doc.id}`)
  }
  lines.push('')

  // Summary of each section
  for (const doc of docs) {
    lines.push(`## ${doc.title}`)
    lines.push('')
    // Take first paragraph
    const firstPara = doc.content.split('\n\n')[0]
    if (firstPara) {
      lines.push(firstPara.replace(/^#+\s+.+$/m, '').trim())
      lines.push('')
    }
  }

  return lines.join('\n')
}

function generateDocsJson(projectName: string, version: string | undefined, docs: DocSection[]): string {
  const data = {
    project: projectName,
    version: version || '0.0.0',
    generatedAt: new Date().toISOString(),
    sections: docs.map(doc => ({
      id: doc.id,
      title: doc.title,
      description: doc.description,
      content: doc.content,
    })),
  }

  return JSON.stringify(data, null, 2)
}

export async function generateCommand(options: GenerateOptions) {
  const cwd = process.cwd()
  const config = await loadConfig(cwd)

  if (!config) {
    console.log(chalk.red('\n❌ No dewey.config.ts found. Run') + chalk.cyan(' dewey init ') + chalk.red('first.\n'))
    process.exit(1)
  }

  const docsPath = join(cwd, config.docs.path)
  const outputPath = options.output || join(cwd, config.docs.output)

  if (!await fileExists(docsPath)) {
    console.log(chalk.red(`\n❌ Docs directory not found: ${config.docs.path}\n`))
    process.exit(1)
  }

  console.log(chalk.blue(`\n🔄 Generating agent files for ${config.project.name}...\n`))

  // Get all available sections
  const files = await readdir(docsPath)
  const availableSections = files
    .filter(f => f.endsWith('.md'))
    .map(f => f.replace('.md', ''))

  // Filter to configured sections (or use all if not specified)
  const sectionsToInclude = config.agent.sections.length > 0
    ? config.agent.sections.filter(s => availableSections.includes(s))
    : availableSections

  const docs = await loadDocs(docsPath, sectionsToInclude)

  // Determine which files to generate
  const generateAll = !options.agentsMd && !options.llmsTxt && !options.docsJson
  const filesToGenerate = {
    agentsMd: generateAll || options.agentsMd,
    llmsTxt: generateAll || options.llmsTxt,
    docsJson: generateAll || options.docsJson,
  }

  // Generate AGENTS.md
  if (filesToGenerate.agentsMd) {
    const content = generateAgentsMd(
      config.project.name,
      config.project.tagline,
      config,
      docs
    )
    const filePath = join(outputPath, 'AGENTS.md')
    await writeFile(filePath, content)
    console.log(chalk.green('✓') + ` Generated ${chalk.cyan('AGENTS.md')}`)
  }

  // Generate llms.txt
  if (filesToGenerate.llmsTxt) {
    const content = generateLlmsTxt(
      config.project.name,
      config.project.tagline,
      docs
    )
    const filePath = join(outputPath, 'llms.txt')
    await writeFile(filePath, content)
    console.log(chalk.green('✓') + ` Generated ${chalk.cyan('llms.txt')}`)
  }

  // Generate docs.json
  if (filesToGenerate.docsJson) {
    const content = generateDocsJson(
      config.project.name,
      config.project.version,
      docs
    )
    const filePath = join(outputPath, 'docs.json')
    await writeFile(filePath, content)
    console.log(chalk.green('✓') + ` Generated ${chalk.cyan('docs.json')}`)
  }

  console.log(chalk.blue('\n✨ Agent files generated!\n'))
  console.log(`Output directory: ${chalk.gray(outputPath)}`)
  console.log(`Included sections: ${chalk.gray(sectionsToInclude.join(', '))}`)
  console.log()
}
