import chalk from 'chalk'
import { mkdir, writeFile, readFile, readdir, access } from 'fs/promises'
import { join, basename, relative } from 'path'
import matter from 'gray-matter'

interface CreateOptions {
  source?: string
  template?: 'nextjs' | 'vite'
  theme?: string
  name?: string
}

interface DocFile {
  id: string
  title: string
  description?: string
  content: string
  order: number
}

interface NavSection {
  title: string
  items: { id: string; title: string }[]
}

async function fileExists(path: string): Promise<boolean> {
  try {
    await access(path)
    return true
  } catch {
    return false
  }
}

async function loadMarkdownDocs(docsPath: string): Promise<DocFile[]> {
  const docs: DocFile[] = []

  if (!await fileExists(docsPath)) {
    return docs
  }

  const files = await readdir(docsPath)

  for (const file of files) {
    if (!file.endsWith('.md')) continue

    const filePath = join(docsPath, file)
    const content = await readFile(filePath, 'utf-8')
    const { data: frontmatter, content: body } = matter(content)
    const id = file.replace('.md', '')

    docs.push({
      id,
      title: (frontmatter.title as string) || id.charAt(0).toUpperCase() + id.slice(1),
      description: frontmatter.description as string | undefined,
      content: body.trim(),
      order: (frontmatter.order as number) || 999,
    })
  }

  // Sort by order
  docs.sort((a, b) => a.order - b.order)

  return docs
}

function generateNavigation(docs: DocFile[]): NavSection[] {
  // Group docs into sections based on order
  // 1-10: Getting Started
  // 11-50: Features
  // 51+: Reference

  const gettingStarted = docs.filter(d => d.order <= 10)
  const features = docs.filter(d => d.order > 10 && d.order <= 50)
  const reference = docs.filter(d => d.order > 50)

  const sections: NavSection[] = []

  if (gettingStarted.length > 0) {
    sections.push({
      title: 'Getting Started',
      items: gettingStarted.map(d => ({ id: d.id, title: d.title })),
    })
  }

  if (features.length > 0) {
    sections.push({
      title: 'Features',
      items: features.map(d => ({ id: d.id, title: d.title })),
    })
  }

  if (reference.length > 0) {
    sections.push({
      title: 'Reference',
      items: reference.map(d => ({ id: d.id, title: d.title })),
    })
  }

  // Fallback: if no sections created, put all in "Documentation"
  if (sections.length === 0 && docs.length > 0) {
    sections.push({
      title: 'Documentation',
      items: docs.map(d => ({ id: d.id, title: d.title })),
    })
  }

  return sections
}

function generateDocsContent(docs: DocFile[]): string {
  const lines: string[] = []

  lines.push('/**')
  lines.push(' * Auto-generated docs content from markdown sources')
  lines.push(' * Generated by: dewey create')
  lines.push(` * Generated at: ${new Date().toISOString()}`)
  lines.push(' */')
  lines.push('')

  for (const doc of docs) {
    const varName = doc.id.replace(/-/g, '_')
    const escapedContent = doc.content
      .replace(/\\/g, '\\\\')
      .replace(/`/g, '\\`')
      .replace(/\$/g, '\\$')

    lines.push(`export const ${varName} = \`${escapedContent}\``)
    lines.push('')
  }

  // Export all docs as a record
  lines.push('export const docs: Record<string, string> = {')
  for (const doc of docs) {
    const varName = doc.id.replace(/-/g, '_')
    lines.push(`  '${doc.id}': ${varName},`)
  }
  lines.push('}')
  lines.push('')

  return lines.join('\n')
}

// Template files for Next.js docs site
const TEMPLATES = {
  'package.json': (projectName: string) => JSON.stringify({
    name: projectName,
    version: '0.1.0',
    private: true,
    scripts: {
      dev: 'next dev --turbopack',
      build: 'next build',
      start: 'next start',
      lint: 'next lint',
    },
    dependencies: {
      '@arach/dewey': '^0.2.0',
      'next': '^16.0.0',
      'react': '^19.0.0',
      'react-dom': '^19.0.0',
    },
    devDependencies: {
      '@tailwindcss/postcss': '^4.0.0',
      '@types/node': '^22.0.0',
      '@types/react': '^19.0.0',
      '@types/react-dom': '^19.0.0',
      'tailwindcss': '^4.0.0',
      'typescript': '^5.0.0',
    },
  }, null, 2),

  'next.config.ts': () => `import type { NextConfig } from 'next'

const nextConfig: NextConfig = {
  output: 'export',
  trailingSlash: true,
  images: {
    unoptimized: true,
  },
}

export default nextConfig
`,

  'tsconfig.json': () => JSON.stringify({
    compilerOptions: {
      lib: ['dom', 'dom.iterable', 'esnext'],
      allowJs: true,
      skipLibCheck: true,
      strict: true,
      noEmit: true,
      esModuleInterop: true,
      module: 'esnext',
      moduleResolution: 'bundler',
      resolveJsonModule: true,
      isolatedModules: true,
      jsx: 'preserve',
      incremental: true,
      plugins: [{ name: 'next' }],
      paths: { '@/*': ['./*'] },
    },
    include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
    exclude: ['node_modules'],
  }, null, 2),

  'postcss.config.mjs': () => `export default {
  plugins: {
    '@tailwindcss/postcss': {},
  },
}
`,

  'app/globals.css': () => `/* Google Fonts - Space Grotesk + Fraunces + JetBrains Mono */
@import url('https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,400;0,9..144,500;0,9..144,600;0,9..144,700;1,9..144,400&family=Space+Grotesk:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap');

@import "tailwindcss";
@import "@arach/dewey/css";

@theme {
  --font-sans: "Space Grotesk", ui-sans-serif, system-ui, -apple-system, sans-serif;
  --font-serif: "Fraunces", ui-serif, Georgia, serif;
  --font-mono: "JetBrains Mono", ui-monospace, SFMono-Regular, "SF Mono", Menlo, monospace;
}

@layer base {
  body {
    font-family: var(--font-sans);
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
  }

  h1, h2, h3 {
    font-family: var(--font-serif);
    font-weight: 600;
  }

  code, pre {
    font-family: var(--font-mono);
  }
}
`,

  'app/layout.tsx': (projectName: string) => `import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: '${projectName} Documentation',
  description: 'Documentation for ${projectName}',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
`,

  'app/page.tsx': () => `import { redirect } from 'next/navigation'

export default function Home() {
  redirect('/docs/overview/')
}
`,

  'app/docs/layout.tsx': () => `export default function DocsLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return children
}
`,

  'app/docs/[[...slug]]/page.tsx': (_nav: NavSection[], defaultPage: string) => `import { docs } from '@/lib/docs-content'
import DocsClientPage from './client'

// Generate static params for all doc pages
export function generateStaticParams() {
  return Object.keys(docs).map((slug) => ({
    slug: [slug],
  }))
}

interface Props {
  params: Promise<{ slug?: string[] }>
}

export default async function DocsPage({ params }: Props) {
  const { slug } = await params
  const pageId = slug?.[0] || '${defaultPage}'

  return <DocsClientPage docs={docs} initialPage={pageId} />
}
`,

  'app/docs/[[...slug]]/client.tsx': (projectName: string, nav: NavSection[]) => `'use client'

import { useRouter } from 'next/navigation'
import dynamic from 'next/dynamic'
import Link from 'next/link'

// Dynamically import DocsApp to avoid SSR issues
const DocsApp = dynamic(
  () => import('@arach/dewey/react').then(mod => mod.DocsApp),
  {
    ssr: false,
    loading: () => (
      <div className="min-h-screen flex items-center justify-center">
        <div className="text-slate-500">Loading docs...</div>
      </div>
    )
  }
)

const navigation = ${JSON.stringify(nav, null, 2)}

// Custom Link component for Next.js
function NextLink({ href, children, ...props }: React.ComponentProps<'a'>) {
  return (
    <Link href={href || '#'} {...props}>
      {children}
    </Link>
  )
}

interface DocsClientPageProps {
  docs: Record<string, string>
  initialPage: string
}

export default function DocsClientPage({ docs, initialPage }: DocsClientPageProps) {
  const router = useRouter()

  const handleNavigate = (pageId: string) => {
    router.push(\`/docs/\${pageId}/\`)
  }

  return (
    <DocsApp
      config={{
        name: '${projectName}',
        tagline: 'Documentation',
        basePath: '/docs',
        homeUrl: '/',
        navigation,
        layout: {
          sidebar: true,
          toc: true,
          header: true,
          prevNext: true,
        },
      }}
      docs={docs}
      currentPage={initialPage}
      onNavigate={handleNavigate}
      providerProps={{
        theme: 'neutral',
        defaultDark: false,
        components: {
          Link: NextLink,
        },
      }}
    />
  )
}
`,
}

export async function createCommand(projectDir: string, options: CreateOptions) {
  const cwd = process.cwd()
  const targetDir = join(cwd, projectDir)
  const sourcePath = options.source ? join(cwd, options.source) : join(cwd, 'docs')
  const projectName = options.name || basename(projectDir)

  console.log(chalk.blue(`\n🚀 Creating Dewey docs site: ${projectName}\n`))

  // Check if target directory exists
  if (await fileExists(targetDir)) {
    console.log(chalk.red(`❌ Directory already exists: ${projectDir}`))
    console.log(chalk.gray('   Use a different name or remove the existing directory.\n'))
    process.exit(1)
  }

  // Load markdown docs from source
  console.log(chalk.gray(`📖 Loading docs from: ${relative(cwd, sourcePath) || '.'}`))
  const docs = await loadMarkdownDocs(sourcePath)

  if (docs.length === 0) {
    console.log(chalk.yellow(`⚠️  No markdown files found in ${sourcePath}`))
    console.log(chalk.gray('   Creating with sample documentation...\n'))

    // Add sample doc
    docs.push({
      id: 'overview',
      title: 'Overview',
      description: 'Welcome to the documentation',
      content: `# Welcome to ${projectName}\n\nThis is your documentation site. Add markdown files to your docs directory to get started.`,
      order: 1,
    })
  }

  console.log(chalk.green(`✓ Found ${docs.length} doc${docs.length === 1 ? '' : 's'}`))

  // Generate navigation from docs
  const navigation = generateNavigation(docs)
  const defaultPage = docs[0]?.id || 'overview'

  // Create directory structure
  console.log(chalk.gray('\n📁 Creating project structure...'))

  await mkdir(targetDir, { recursive: true })
  await mkdir(join(targetDir, 'app', 'docs', '[[...slug]]'), { recursive: true })
  await mkdir(join(targetDir, 'lib'), { recursive: true })

  // Write template files
  const files: [string, string][] = [
    ['package.json', TEMPLATES['package.json'](projectName)],
    ['next.config.ts', TEMPLATES['next.config.ts']()],
    ['tsconfig.json', TEMPLATES['tsconfig.json']()],
    ['postcss.config.mjs', TEMPLATES['postcss.config.mjs']()],
    ['app/globals.css', TEMPLATES['app/globals.css']()],
    ['app/layout.tsx', TEMPLATES['app/layout.tsx'](projectName)],
    ['app/page.tsx', TEMPLATES['app/page.tsx']()],
    ['app/docs/layout.tsx', TEMPLATES['app/docs/layout.tsx']()],
    ['app/docs/[[...slug]]/page.tsx', TEMPLATES['app/docs/[[...slug]]/page.tsx'](navigation, defaultPage)],
    ['app/docs/[[...slug]]/client.tsx', TEMPLATES['app/docs/[[...slug]]/client.tsx'](projectName, navigation)],
    ['lib/docs-content/index.ts', generateDocsContent(docs)],
  ]

  for (const [filePath, content] of files) {
    const fullPath = join(targetDir, filePath)
    const dir = join(targetDir, filePath.split('/').slice(0, -1).join('/'))
    await mkdir(dir, { recursive: true })
    await writeFile(fullPath, content)
    console.log(chalk.green('✓') + ` ${filePath}`)
  }

  // Create .gitignore
  await writeFile(join(targetDir, '.gitignore'), `# Dependencies
node_modules
.pnpm-store

# Next.js
.next
out

# Misc
.DS_Store
*.log
`)
  console.log(chalk.green('✓') + ' .gitignore')

  console.log(chalk.blue('\n✨ Docs site created!\n'))

  console.log('Next steps:')
  console.log(chalk.gray(`  cd ${projectDir}`))
  console.log(chalk.gray('  pnpm install'))
  console.log(chalk.gray('  pnpm dev'))
  console.log('')
  console.log('Your docs will be available at:')
  console.log(chalk.cyan('  http://localhost:3000/docs/'))
  console.log('')

  if (docs.length > 0) {
    console.log('Included documentation:')
    for (const doc of docs) {
      console.log(chalk.gray(`  - ${doc.title} (${doc.id}.md)`))
    }
    console.log('')
  }

  console.log(chalk.gray('To add more docs, create markdown files and run:'))
  console.log(chalk.cyan(`  dewey create ${projectDir} --source ./docs`))
  console.log('')
}
