import chalk from 'chalk'
import { mkdir, writeFile, readFile, readdir, access } from 'fs/promises'
import { join, basename, relative } from 'path'
import matter from 'gray-matter'

interface CreateOptions {
  source?: string
  template?: 'nextjs' | 'vite'
  theme?: string
  name?: string
}

interface DocFile {
  id: string
  title: string
  description?: string
  content: string
  order: number
}

interface NavSection {
  title: string
  items: { id: string; title: string; description?: string }[]
}

const VALID_THEMES = ['neutral', 'ocean', 'emerald', 'purple', 'dusk', 'rose', 'github', 'warm'] as const
type ThemeName = typeof VALID_THEMES[number]

function resolveTheme(theme?: string): ThemeName {
  if (!theme) return 'neutral'
  if (VALID_THEMES.includes(theme as ThemeName)) return theme as ThemeName
  console.log(chalk.yellow(`⚠️  Unknown theme "${theme}". Falling back to "neutral".`))
  return 'neutral'
}

function resolveTemplate(template?: string): 'nextjs' | 'vite' {
  if (template === 'nextjs' || template === 'vite') return template
  return 'vite'
}

async function fileExists(path: string): Promise<boolean> {
  try {
    await access(path)
    return true
  } catch {
    return false
  }
}

async function loadMarkdownDocs(docsPath: string): Promise<DocFile[]> {
  const docs: DocFile[] = []

  if (!await fileExists(docsPath)) {
    return docs
  }

  const files = await readdir(docsPath)

  for (const file of files) {
    if (!file.endsWith('.md')) continue

    const filePath = join(docsPath, file)
    const content = await readFile(filePath, 'utf-8')
    const { data: frontmatter, content: body } = matter(content)
    const id = file.replace('.md', '')

    docs.push({
      id,
      title: (frontmatter.title as string) || id.charAt(0).toUpperCase() + id.slice(1),
      description: frontmatter.description as string | undefined,
      content: body.trim(),
      order: (frontmatter.order as number) || 999,
    })
  }

  // Sort by order
  docs.sort((a, b) => a.order - b.order)

  return docs
}

function generateNavigation(docs: DocFile[]): NavSection[] {
  // Group docs into sections based on order
  // 1-10: Getting Started
  // 11-50: Features
  // 51+: Reference

  const gettingStarted = docs.filter(d => d.order <= 10)
  const features = docs.filter(d => d.order > 10 && d.order <= 50)
  const reference = docs.filter(d => d.order > 50)

  const sections: NavSection[] = []

  if (gettingStarted.length > 0) {
    sections.push({
      title: 'Getting Started',
      items: gettingStarted.map(d => ({ id: d.id, title: d.title, description: d.description })),
    })
  }

  if (features.length > 0) {
    sections.push({
      title: 'Features',
      items: features.map(d => ({ id: d.id, title: d.title, description: d.description })),
    })
  }

  if (reference.length > 0) {
    sections.push({
      title: 'Reference',
      items: reference.map(d => ({ id: d.id, title: d.title, description: d.description })),
    })
  }

  // Fallback: if no sections created, put all in "Documentation"
  if (sections.length === 0 && docs.length > 0) {
    sections.push({
      title: 'Documentation',
      items: docs.map(d => ({ id: d.id, title: d.title, description: d.description })),
    })
  }

  return sections
}

function generateDocsContent(docs: DocFile[]): string {
  const lines: string[] = []

  lines.push('/**')
  lines.push(' * Auto-generated docs content from markdown sources')
  lines.push(' * Generated by: dewey create')
  lines.push(` * Generated at: ${new Date().toISOString()}`)
  lines.push(' */')
  lines.push('')

  for (const doc of docs) {
    const varName = doc.id.replace(/-/g, '_')
    const escapedContent = doc.content
      .replace(/\\/g, '\\\\')
      .replace(/`/g, '\\`')
      .replace(/\$/g, '\\$')

    lines.push(`export const ${varName} = \`${escapedContent}\``)
    lines.push('')
  }

  // Export all docs as a record
  lines.push('export const docs: Record<string, string> = {')
  for (const doc of docs) {
    const varName = doc.id.replace(/-/g, '_')
    lines.push(`  '${doc.id}': ${varName},`)
  }
  lines.push('}')
  lines.push('')

  return lines.join('\n')
}

// Template files for Next.js docs site
const NEXT_TEMPLATES = {
  'package.json': (projectName: string) => JSON.stringify({
    name: projectName,
    version: '0.1.0',
    private: true,
    scripts: {
      dev: 'next dev --turbopack',
      build: 'next build',
      start: 'next start',
      lint: 'next lint',
    },
    dependencies: {
      '@arach/dewey': '^0.2.0',
      'next': '^16.0.0',
      'react': '^19.0.0',
      'react-dom': '^19.0.0',
    },
    devDependencies: {
      '@tailwindcss/postcss': '^4.0.0',
      '@types/node': '^22.0.0',
      '@types/react': '^19.0.0',
      '@types/react-dom': '^19.0.0',
      'tailwindcss': '^4.0.0',
      'typescript': '^5.0.0',
    },
  }, null, 2),

  'next.config.ts': () => `import type { NextConfig } from 'next'

const nextConfig: NextConfig = {
  output: 'export',
  trailingSlash: true,
  images: {
    unoptimized: true,
  },
}

export default nextConfig
`,

  'tsconfig.json': () => JSON.stringify({
    compilerOptions: {
      lib: ['dom', 'dom.iterable', 'esnext'],
      allowJs: true,
      skipLibCheck: true,
      strict: true,
      noEmit: true,
      esModuleInterop: true,
      module: 'esnext',
      moduleResolution: 'bundler',
      resolveJsonModule: true,
      isolatedModules: true,
      jsx: 'preserve',
      incremental: true,
      plugins: [{ name: 'next' }],
      paths: { '@/*': ['./*'] },
    },
    include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
    exclude: ['node_modules'],
  }, null, 2),

  'postcss.config.mjs': () => `export default {
  plugins: {
    '@tailwindcss/postcss': {},
  },
}
`,

  'app/globals.css': (theme: ThemeName) => `/* Google Fonts - Space Grotesk + Fraunces + JetBrains Mono */
@import url('https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,400;0,9..144,500;0,9..144,600;0,9..144,700;1,9..144,400&family=Space+Grotesk:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap');

@import "tailwindcss";
@import "@arach/dewey/css";
${theme === 'neutral' ? '' : `@import "@arach/dewey/css/colors/${theme}.css";`}

@theme {
  --font-sans: "Space Grotesk", ui-sans-serif, system-ui, -apple-system, sans-serif;
  --font-serif: "Fraunces", ui-serif, Georgia, serif;
  --font-mono: "JetBrains Mono", ui-monospace, SFMono-Regular, "SF Mono", Menlo, monospace;
}

@layer base {
  body {
    font-family: var(--font-sans);
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
  }

  h1, h2, h3 {
    font-family: var(--font-serif);
    font-weight: 600;
  }

  code, pre {
    font-family: var(--font-mono);
  }
}
`,

  'app/layout.tsx': (projectName: string) => `import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: '${projectName} Documentation',
  description: 'Documentation for ${projectName}',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
`,

  'app/page.tsx': () => `import { redirect } from 'next/navigation'

export default function Home() {
  redirect('/docs/overview/')
}
`,

  'app/docs/layout.tsx': () => `export default function DocsLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return children
}
`,

  'app/docs/[[...slug]]/page.tsx': (_nav: NavSection[], defaultPage: string) => `import { docs } from '@/lib/docs-content'
import DocsClientPage from './client'

// Generate static params for all doc pages
export function generateStaticParams() {
  return Object.keys(docs).map((slug) => ({
    slug: [slug],
  }))
}

interface Props {
  params: Promise<{ slug?: string[] }>
}

export default async function DocsPage({ params }: Props) {
  const { slug } = await params
  const pageId = slug?.[0] || '${defaultPage}'

  return <DocsClientPage docs={docs} initialPage={pageId} />
}
`,

  'app/docs/[[...slug]]/client.tsx': (projectName: string, nav: NavSection[], theme: ThemeName) => `'use client'

import { useRouter } from 'next/navigation'
import dynamic from 'next/dynamic'
import Link from 'next/link'

// Dynamically import DocsApp to avoid SSR issues
const DocsApp = dynamic(
  () => import('@arach/dewey/react').then(mod => mod.DocsApp),
  {
    ssr: false,
    loading: () => (
      <div className="min-h-screen flex items-center justify-center">
        <div className="text-slate-500">Loading docs...</div>
      </div>
    )
  }
)

const navigation = ${JSON.stringify(nav, null, 2)}

// Custom Link component for Next.js
function NextLink({ href, children, ...props }: React.ComponentProps<'a'>) {
  return (
    <Link href={href || '#'} {...props}>
      {children}
    </Link>
  )
}

interface DocsClientPageProps {
  docs: Record<string, string>
  initialPage: string
}

export default function DocsClientPage({ docs, initialPage }: DocsClientPageProps) {
  const router = useRouter()

  const handleNavigate = (pageId: string) => {
    router.push(\`/docs/\${pageId}/\`)
  }

  return (
    <DocsApp
      config={{
        name: '${projectName}',
        tagline: 'Documentation',
        basePath: '/docs',
        homeUrl: '/',
        navigation,
        layout: {
          sidebar: true,
          toc: true,
          header: true,
          prevNext: true,
          breadcrumbs: true,
        },
      }}
      docs={docs}
      currentPage={initialPage}
      onNavigate={handleNavigate}
      providerProps={{
        theme: '${theme}',
        defaultDark: false,
        components: {
          Link: NextLink,
        },
      }}
    />
  )
}
`,
}

// Template files for Vite docs site
const VITE_TEMPLATES = {
  'package.json': (projectName: string) => JSON.stringify({
    name: projectName,
    version: '0.1.0',
    private: true,
    type: 'module',
    scripts: {
      dev: 'vite',
      build: 'tsc -b && vite build',
      preview: 'vite preview',
    },
    dependencies: {
      '@arach/dewey': '^0.2.0',
      'react': '^19.0.0',
      'react-dom': '^19.0.0',
      'react-router-dom': '^7.0.0',
    },
    devDependencies: {
      '@types/react': '^19.0.0',
      '@types/react-dom': '^19.0.0',
      '@vitejs/plugin-react': '^4.3.0',
      'typescript': '^5.5.0',
      'vite': '^6.0.0',
    },
  }, null, 2),

  'vite.config.ts': () => `import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
})
`,

  'tsconfig.json': () => JSON.stringify({
    compilerOptions: {
      target: 'ES2020',
      useDefineForClassFields: true,
      lib: ['ES2020', 'DOM', 'DOM.Iterable'],
      module: 'ESNext',
      skipLibCheck: true,
      moduleResolution: 'bundler',
      allowImportingTsExtensions: true,
      resolveJsonModule: true,
      isolatedModules: true,
      noEmit: true,
      jsx: 'react-jsx',
      strict: true,
    },
    include: ['src'],
  }, null, 2),

  'index.html': (projectName: string) => `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${projectName} Docs</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`,

  'src/main.tsx': () => `import React from 'react'
import ReactDOM from 'react-dom/client'
import { BrowserRouter } from 'react-router-dom'
import App from './App'
import './index.css'

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <BrowserRouter>
      <App />
    </BrowserRouter>
  </React.StrictMode>
)
`,

  'src/index.css': (theme: ThemeName) => `/* Fonts (Space Grotesk + Fraunces + JetBrains Mono) */
@import url('https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,400;0,9..144,500;0,9..144,600;0,9..144,700;1,9..144,400&family=Space+Grotesk:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap');

@import "@arach/dewey/css";
${theme === 'neutral' ? '' : `@import "@arach/dewey/css/colors/${theme}.css";`}

:root {
  --dw-font-sans: "Space Grotesk", ui-sans-serif, system-ui, -apple-system, sans-serif;
  --dw-font-serif: "Fraunces", ui-serif, Georgia, serif;
  --dw-font-mono: "JetBrains Mono", ui-monospace, SFMono-Regular, "SF Mono", Menlo, monospace;
}

body {
  margin: 0;
  background: var(--dw-background);
  color: var(--dw-foreground);
}

.dw-home {
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 3rem;
  background: var(--dw-background);
  color: var(--dw-foreground);
  font-family: var(--dw-font-sans);
}

.dw-home-inner {
  max-width: 48rem;
  text-align: center;
}

.dw-home-title {
  font-family: var(--dw-font-serif);
  font-size: 2.5rem;
  margin-bottom: 0.5rem;
}

.dw-home-link {
  color: var(--dw-primary);
  text-decoration: none;
  font-weight: 600;
}
`,

  'src/App.tsx': () => `import { Routes, Route, Navigate } from 'react-router-dom'
import { siteConfig } from './site.config'
import DocsPage from './pages/Docs'
import Home from './pages/Home'

export default function App() {
  return (
    <Routes>
      <Route path="/" element={<Home />} />
      <Route path={\`\${siteConfig.basePath}/*\`} element={<DocsPage />} />
      <Route path="*" element={<Navigate to={siteConfig.basePath} replace />} />
    </Routes>
  )
}
`,

  'src/pages/Home.tsx': (projectName: string) => `import { Link } from 'react-router-dom'
import { siteConfig } from '../site.config'

export default function Home() {
  return (
    <div className="dw-home">
      <div className="dw-home-inner">
        <h1 className="dw-home-title">${projectName}</h1>
        <p style={{ color: 'var(--dw-muted-foreground)', marginBottom: '1.5rem' }}>
          Main site placeholder. Customize this page or link to your real homepage.
        </p>
        <Link className="dw-home-link" to={siteConfig.basePath}>
          Go to documentation →
        </Link>
      </div>
    </div>
  )
}
`,

  'src/pages/Docs.tsx': () => `import type { ComponentProps } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { DocsApp } from '@arach/dewey/react'
import { docs } from '../lib/docs-content'
import { siteConfig, siteTheme, defaultPage } from '../site.config'

function RouterLink({
  href,
  ...props
}: ComponentProps<'a'> & { href: string }) {
  return <Link to={href} {...props} />
}

export default function DocsPage() {
  const navigate = useNavigate()
  const params = useParams()
  const slug = params['*']?.split('/')[0]
  const pageId = slug && slug.length > 0 ? slug : defaultPage

  return (
    <DocsApp
      config={siteConfig}
      docs={docs}
      currentPage={pageId}
      onNavigate={(nextPage) => navigate(\`\${siteConfig.basePath}/\${nextPage}\`)}
      providerProps={{
        theme: siteTheme,
        components: { Link: RouterLink },
      }}
    />
  )
}
`,

  'src/site.config.ts': (projectName: string, navigation: NavSection[], defaultPage: string, theme: ThemeName) => `import type { DocsAppConfig } from '@arach/dewey'

export const siteTheme = '${theme}' as const
export const defaultPage = '${defaultPage}'

export const siteConfig = {
  name: '${projectName}',
  tagline: 'Documentation',
  basePath: '/docs',
  homeUrl: '/',
  navigation: ${JSON.stringify(navigation, null, 2)},
  layout: {
    sidebar: true,
    toc: true,
    header: true,
    prevNext: true,
    breadcrumbs: true,
  },
} satisfies DocsAppConfig
`,
}

export async function createCommand(projectDir: string, options: CreateOptions) {
  const cwd = process.cwd()
  const targetDir = join(cwd, projectDir)
  const sourcePath = options.source ? join(cwd, options.source) : join(cwd, 'docs')
  const projectName = options.name || basename(projectDir)
  const template = resolveTemplate(options.template)
  const theme = resolveTheme(options.theme)

  console.log(chalk.blue(`\n🚀 Creating Dewey docs site: ${projectName}\n`))

  // Check if target directory exists
  if (await fileExists(targetDir)) {
    console.log(chalk.red(`❌ Directory already exists: ${projectDir}`))
    console.log(chalk.gray('   Use a different name or remove the existing directory.\n'))
    process.exit(1)
  }

  // Load markdown docs from source
  console.log(chalk.gray(`📖 Loading docs from: ${relative(cwd, sourcePath) || '.'}`))
  const docs = await loadMarkdownDocs(sourcePath)

  if (docs.length === 0) {
    console.log(chalk.yellow(`⚠️  No markdown files found in ${sourcePath}`))
    console.log(chalk.gray('   Creating with sample documentation...\n'))

    // Add sample doc
    docs.push({
      id: 'overview',
      title: 'Overview',
      description: 'Welcome to the documentation',
      content: `# Welcome to ${projectName}\n\nThis is your documentation site. Add markdown files to your docs directory to get started.`,
      order: 1,
    })
  }

  console.log(chalk.green(`✓ Found ${docs.length} doc${docs.length === 1 ? '' : 's'}`))

  // Generate navigation from docs
  const navigation = generateNavigation(docs)
  const defaultPage = docs[0]?.id || 'overview'

  // Create directory structure
  console.log(chalk.gray('\n📁 Creating project structure...'))

  await mkdir(targetDir, { recursive: true })

  // Write template files
  const files: [string, string][] = template === 'nextjs'
    ? [
      ['package.json', NEXT_TEMPLATES['package.json'](projectName)],
      ['next.config.ts', NEXT_TEMPLATES['next.config.ts']()],
      ['tsconfig.json', NEXT_TEMPLATES['tsconfig.json']()],
      ['postcss.config.mjs', NEXT_TEMPLATES['postcss.config.mjs']()],
      ['app/globals.css', NEXT_TEMPLATES['app/globals.css'](theme)],
      ['app/layout.tsx', NEXT_TEMPLATES['app/layout.tsx'](projectName)],
      ['app/page.tsx', NEXT_TEMPLATES['app/page.tsx']()],
      ['app/docs/layout.tsx', NEXT_TEMPLATES['app/docs/layout.tsx']()],
      ['app/docs/[[...slug]]/page.tsx', NEXT_TEMPLATES['app/docs/[[...slug]]/page.tsx'](navigation, defaultPage)],
      ['app/docs/[[...slug]]/client.tsx', NEXT_TEMPLATES['app/docs/[[...slug]]/client.tsx'](projectName, navigation, theme)],
      ['lib/docs-content/index.ts', generateDocsContent(docs)],
    ]
    : [
      ['package.json', VITE_TEMPLATES['package.json'](projectName)],
      ['vite.config.ts', VITE_TEMPLATES['vite.config.ts']()],
      ['tsconfig.json', VITE_TEMPLATES['tsconfig.json']()],
      ['index.html', VITE_TEMPLATES['index.html'](projectName)],
      ['src/main.tsx', VITE_TEMPLATES['src/main.tsx']()],
      ['src/index.css', VITE_TEMPLATES['src/index.css'](theme)],
      ['src/App.tsx', VITE_TEMPLATES['src/App.tsx']()],
      ['src/pages/Home.tsx', VITE_TEMPLATES['src/pages/Home.tsx'](projectName)],
      ['src/pages/Docs.tsx', VITE_TEMPLATES['src/pages/Docs.tsx']()],
      ['src/site.config.ts', VITE_TEMPLATES['src/site.config.ts'](projectName, navigation, defaultPage, theme)],
      ['src/lib/docs-content.ts', generateDocsContent(docs)],
    ]

  for (const [filePath, content] of files) {
    const fullPath = join(targetDir, filePath)
    const dir = join(targetDir, filePath.split('/').slice(0, -1).join('/'))
    await mkdir(dir, { recursive: true })
    await writeFile(fullPath, content)
    console.log(chalk.green('✓') + ` ${filePath}`)
  }

  // Create .gitignore
  const gitignore = template === 'nextjs'
    ? `# Dependencies
node_modules
.pnpm-store

# Next.js
.next
out

# Misc
.DS_Store
*.log
`
    : `# Dependencies
node_modules
.pnpm-store

# Vite
dist

# Misc
.DS_Store
*.log
`

  await writeFile(join(targetDir, '.gitignore'), gitignore)
  console.log(chalk.green('✓') + ' .gitignore')

  console.log(chalk.blue('\n✨ Docs site created!\n'))

  console.log('Next steps:')
  console.log(chalk.gray(`  cd ${projectDir}`))
  console.log(chalk.gray('  pnpm install'))
  console.log(chalk.gray('  pnpm dev'))
  console.log('')
  console.log('Your docs will be available at:')
  console.log(chalk.cyan(template === 'nextjs'
    ? '  http://localhost:3000/docs/'
    : '  http://localhost:5173/docs/'))
  console.log('')

  if (docs.length > 0) {
    console.log('Included documentation:')
    for (const doc of docs) {
      console.log(chalk.gray(`  - ${doc.title} (${doc.id}.md)`))
    }
    console.log('')
  }

  console.log(chalk.gray('To add more docs, create markdown files and run:'))
  console.log(chalk.cyan(`  dewey create ${projectDir} --source ./docs`))
  console.log('')
}
