import chalk from 'chalk'
import { access } from 'fs/promises'
import { resolve } from 'path'
import { loadConfig } from '../config.js'
import {
  buildDocsManifest,
  discoverDocuments,
  type DiscoveredDocument,
} from '../docs-manifest.js'
import { DEWEY_VERSION, getGeneratedAt } from '../version.js'
import { buildAgentArtifactFiles, type AgentManifest } from '../agent-artifacts.js'
import {
  applyGenerationPlan,
  isOutputInsideSource,
  planGeneratedArtifacts,
  type GeneratedArtifact,
  type GenerationAction,
  type GenerationScope,
} from '../generation-plan.js'

export interface GenerateOptions {
  output?: string
  source?: string
  agentsMd?: boolean
  llmsTxt?: boolean
  docsJson?: boolean
  installMd?: boolean
  agentArtifacts?: boolean
  dryRun?: boolean
  overwrite?: boolean
}

type DocSection = DiscoveredDocument

async function fileExists(path: string): Promise<boolean> {
  try {
    await access(path)
    return true
  } catch {
    return false
  }
}

export async function discoverMarkdownSections(docsPath: string): Promise<string[]> {
  const docs = await discoverDocuments({ rootDir: docsPath, docsDir: docsPath, audience: 'human' })
  return docs.filter(doc => doc.extension === '.md').map(doc => doc.id).sort()
}

export async function loadDocs(
  cwd: string,
  docsPath: string,
  docsRelativePath: string,
  sections: string[],
): Promise<DocSection[]> {
  void docsRelativePath // retained for source compatibility; root-relative paths are canonical
  const selected = new Set(sections)
  return (await discoverDocuments({ rootDir: cwd, docsDir: docsPath, audience: 'human' }))
    .filter(doc => doc.extension === '.md' && selected.has(doc.id))
}

function generateAgentsMd(projectName: string, tagline: string | undefined, config: Awaited<ReturnType<typeof loadConfig>>, docs: DocSection[]): string {
  if (!config) return ''

  const lines: string[] = []

  // Header
  lines.push(`# ${projectName}`)
  lines.push('')
  if (tagline) {
    lines.push(`> ${tagline}`)
    lines.push('')
  }

  // Critical context
  if (config.agent.criticalContext.length > 0) {
    lines.push('## Critical Context')
    lines.push('')
    lines.push('**IMPORTANT:** Read these rules before making any changes:')
    lines.push('')
    for (const rule of config.agent.criticalContext) {
      lines.push(`- ${rule}`)
    }
    lines.push('')
  }

  // Project structure / entry points
  if (Object.keys(config.agent.entryPoints).length > 0) {
    lines.push('## Project Structure')
    lines.push('')
    lines.push('| Component | Path |')
    lines.push('|-----------|------|')
    for (const [name, path] of Object.entries(config.agent.entryPoints)) {
      const displayName = name.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ')
      lines.push(`| ${displayName} | \`${path}\` |`)
    }
    lines.push('')
  }

  // Navigation rules
  if (config.agent.rules.length > 0) {
    lines.push('## Quick Navigation')
    lines.push('')
    for (const rule of config.agent.rules) {
      lines.push(`- Working with **${rule.pattern}**? → ${rule.instruction}`)
    }
    lines.push('')
  }

  // Documentation sections
  for (const doc of docs) {
    lines.push(`## ${doc.title}`)
    lines.push('')
    if (doc.description) {
      lines.push(`> ${doc.description}`)
      lines.push('')
    }
    lines.push(doc.content)
    lines.push('')
  }

  // Footer
  lines.push('---')
  const generatedAt = getGeneratedAt()
  const generatedDate = generatedAt ? ` | Last updated: ${generatedAt.split('T')[0]}` : ''
  lines.push(`Generated by [Dewey ${DEWEY_VERSION}](https://github.com/arach/dewey)${generatedDate}`)

  return lines.join('\n')
}

function cleanSummaryMarkdown(value: string): string {
  return value
    .replace(/^>\s?/gm, '')
    .replace(/^[-*+]\s+/gm, '')
    .replace(/^\d+[.)]\s+/gm, '')
    .replace(/`([^`]+)`/g, '$1')
    .replace(/!\[([^\]]*)\]\([^)]+\)/g, '$1')
    .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
    .replace(/[\*_~]/g, '')
    .replace(/\s+/g, ' ')
    .trim()
}

export function extractLlmsSummary(doc: Pick<DocSection, 'description' | 'content' | 'title'>): string {
  if (doc.description?.trim()) return cleanSummaryMarkdown(doc.description).slice(0, 320)

  const content = doc.content
    .replace(/```[\s\S]*?```/g, '')
    .replace(/<!--([\s\S]*?)-->/g, '')
    .trim()

  const summaryContent = content.replace(/^#{1,6}\s+.*$/gm, '').trim()
  const blocks = summaryContent.split(/\n{2,}/).map(block => block.trim()).filter(Boolean)
  const prose = blocks.find(block =>
    !block.startsWith('#') &&
    !block.startsWith('|') &&
    !/^[-*+]\s+/.test(block) &&
    !/^\d+[.)]\s+/.test(block),
  )
  if (prose) return cleanSummaryMarkdown(prose).slice(0, 320)

  const list = blocks.find(block => /^([-*+]\s+|\d+[.)]\s+)/.test(block))
  if (list) {
    const items = list.split('\n').filter(line => /^\s*([-*+]\s+|\d+[.)]\s+)/.test(line)).slice(0, 3)
    const summary = items.map(cleanSummaryMarkdown).filter(Boolean).join('; ')
    if (summary) return summary.slice(0, 320)
  }

  const heading = content.match(/^#{1,6}\s+(.+)$/m)?.[1]
  return cleanSummaryMarkdown(heading || doc.title).slice(0, 320)
}

function generateLlmsTxt(
  projectName: string,
  tagline: string | undefined,
  docs: DocSection[],
  agentManifest?: AgentManifest,
): string {
  const lines: string[] = []

  lines.push(`# ${projectName}`)
  lines.push('')
  if (tagline) {
    lines.push(`> ${tagline}`)
    lines.push('')
  }

  lines.push('## Documentation')
  lines.push('')
  for (const doc of docs) {
    lines.push(`- ${doc.title}: /docs/${doc.id}`)
  }
  lines.push('')

  if (agentManifest) {
    const link = (key: string) => {
      const value = agentManifest.artifacts[key]
      return typeof value === 'string' ? value : ''
    }
    lines.push('## Agent Retrieval Artifacts')
    lines.push('')
    lines.push(`- Discovery manifest: ${link('manifest')}`)
    lines.push(`- Docs with markdown: ${link('docs')}`)
    lines.push(`- Prompt registry: ${link('prompts')}`)
    lines.push(`- Retrieval index: ${link('context')}`)
    lines.push(`- Raw markdown base: ${link('rawMarkdownBase')}`)
    const bundles = agentManifest.artifacts.bundles
    if (typeof bundles !== 'string') {
      lines.push(`- Core bundle: ${bundles.core}`)
      lines.push(`- Prompt bundle: ${bundles.prompts}`)
    }
    lines.push('')
  }

  // Summary of each section
  for (const doc of docs) {
    lines.push(`## ${doc.title}`)
    lines.push('')
    lines.push(extractLlmsSummary(doc))
    lines.push('')
  }

  // Footer
  lines.push('---')
  lines.push(`Generated by Dewey ${DEWEY_VERSION} | https://github.com/arach/dewey`)

  return lines.join('\n')
}

function generateDocsJson(
  projectName: string,
  version: string | undefined,
  tagline: string | undefined,
  docs: DocSection[],
): string {
  const data = buildDocsManifest(projectName, version, tagline, docs)

  return JSON.stringify(data, null, 2)
}

/**
 * Generate install.md following the installmd.org standard
 * @see https://installmd.org
 */
function generateInstallMd(config: Awaited<ReturnType<typeof loadConfig>>, docs: DocSection[]): string {
  if (!config) return ''

  const lines: string[] = []
  const configuredName = config.project.name.trim()
  // Scoped npm names are already install identifiers; do not slugify away `/` or `@`.
  const projectName = /^@[^/\s]+\/[^/\s]+$/.test(configuredName)
    ? configuredName
    : configuredName.toLowerCase().replace(/\s+/g, '-')
  const install = config.install

  // H1 with lowercase hyphenated name
  lines.push(`# ${projectName}`)
  lines.push('')

  // Blockquote description
  if (config.project.tagline) {
    lines.push(`> ${config.project.tagline}`)
    lines.push('')
  }

  // Agent instruction
  lines.push(`You are an expert at installing ${config.project.name}. Execute these steps autonomously`)
  lines.push('and inform the user of any decisions made. Request approval before running')
  lines.push('installation commands.')
  lines.push('')

  // OBJECTIVE section
  lines.push('## OBJECTIVE')
  lines.push('')
  if (install?.objective) {
    lines.push(install.objective)
  } else {
    lines.push(`Install and configure ${config.project.name}.`)
  }
  lines.push('')

  // DONE WHEN section
  lines.push('## DONE WHEN')
  lines.push('')
  if (install?.doneWhen) {
    lines.push(`\`${install.doneWhen.command}\`${install.doneWhen.expectedOutput ? ` returns ${install.doneWhen.expectedOutput}` : ' completes successfully'}`)
  } else {
    // Try to infer from project type
    switch (config.project.type) {
      case 'npm-package':
        lines.push(`\`npm list ${projectName}\` shows the package installed.`)
        break
      case 'cli-tool':
        lines.push(`\`${projectName} --version\` returns a version number.`)
        break
      case 'macos-app':
        lines.push(`The app is installed in /Applications and can be launched.`)
        break
      default:
        lines.push(`Installation completes without errors.`)
    }
  }
  lines.push('')

  // TODO section (checklist)
  lines.push('## TODO')
  lines.push('')
  if (install?.steps && install.steps.length > 0) {
    for (const step of install.steps) {
      lines.push(`- [ ] ${step.description}`)
    }
  } else {
    // Default steps based on project type
    lines.push('- [ ] Verify prerequisites')
    lines.push('- [ ] Install the package')
    if (config.project.type !== 'npm-package') {
      lines.push('- [ ] Configure initial settings')
    }
    lines.push('- [ ] Verify installation')
  }
  lines.push('')

  // Prerequisites section (if any)
  if (install?.prerequisites && install.prerequisites.length > 0) {
    lines.push('## Prerequisites')
    lines.push('')
    for (const prereq of install.prerequisites) {
      lines.push(`- ${prereq}`)
    }
    lines.push('')
  }

  // Detailed step sections
  if (install?.steps && install.steps.length > 0) {
    install.steps.forEach((step, index) => {
      lines.push(`## Step ${index + 1}: ${step.description}`)
      lines.push('')
      if (step.command) {
        lines.push('```bash')
        lines.push(step.command)
        lines.push('```')
        lines.push('')
      }
      if (step.alternatives && step.alternatives.length > 0) {
        for (const alt of step.alternatives) {
          lines.push(`**Alternative for ${alt.condition}:**`)
          lines.push('```bash')
          lines.push(alt.command)
          lines.push('```')
          lines.push('')
        }
      }
    })
  } else {
    // Prefer a documented installation section, then fall back to a complete
    // project-type recipe even when no quickstart page exists.
    const quickstart = docs.find(d => d.id === 'quickstart')
    const installMatch = quickstart?.content.match(/## Installation[\s\S]*?(?=##|$)/)
    lines.push('## Installation')
    lines.push('')
    if (installMatch) {
      lines.push(installMatch[0].replace('## Installation', '').trim())
    } else {
      switch (config.project.type) {
        case 'npm-package':
        case 'react-library':
          lines.push('```bash')
          lines.push('# Using Bun (recommended)')
          lines.push(`bun add ${projectName}`)
          lines.push('')
          lines.push('# Using npm')
          lines.push(`npm install ${projectName}`)
          lines.push('')
          lines.push('# Using yarn')
          lines.push(`yarn add ${projectName}`)
          lines.push('```')
          break
        case 'cli-tool':
          lines.push('```bash')
          lines.push('# Using Bun')
          lines.push(`bun add -g ${projectName}`)
          lines.push('')
          lines.push('# Using npm')
          lines.push(`npm install -g ${projectName}`)
          lines.push('```')
          break
        case 'macos-app':
          lines.push('```bash')
          lines.push('# Using Homebrew')
          lines.push(`brew install --cask ${projectName}`)
          lines.push('')
          lines.push('# Or build from source')
          lines.push('swift build -c release')
          lines.push('```')
          break
        default:
          lines.push('See documentation for installation instructions.')
      }
    }
    lines.push('')
  }

  // EXECUTE NOW section
  lines.push('## EXECUTE NOW')
  lines.push('')
  lines.push('Proceed with installation following the TODO checklist above.')
  lines.push('')

  // Footer
  lines.push('---')
  lines.push(`Generated by [Dewey ${DEWEY_VERSION}](https://github.com/arach/dewey) | [installmd.org](https://installmd.org)`)

  return lines.join('\n')
}

export async function generateCommand(options: GenerateOptions) {
  const cwd = process.cwd()
  const config = await loadConfig(cwd)

  if (!config) {
    console.log(chalk.red('\n❌ No dewey.config.ts found. Run') + chalk.cyan(' dewey init ') + chalk.red('first.\n'))
    process.exit(1)
  }

  const docsPath = resolve(cwd, options.source || config.docs.path)
  const outputPath = resolve(cwd, options.output || config.docs.output)

  if (!await fileExists(docsPath)) {
    console.log(chalk.red(`\n❌ Docs directory not found: ${config.docs.path}\n`))
    process.exit(1)
  }

  if (isOutputInsideSource(docsPath, outputPath)) {
    throw new Error(
      `Output directory must not be the docs source or one of its descendants: ${outputPath}`,
    )
  }

  console.log(chalk.blue(`\n🔄 Generating agent files for ${config.project.name}...\n`))

  // Discover and parse once; every generated surface consumes this canonical set.
  const discoveredDocs = (await discoverDocuments({ rootDir: cwd, docsDir: docsPath, audience: 'human' }))
    .filter(doc => doc.extension === '.md')
  const availableSections = discoveredDocs.map(doc => doc.id).sort()
  if (availableSections.length === 0) {
    console.warn(chalk.yellow(`⚠ No human Markdown documents found in ${docsPath}`))
  }

  const missingConfiguredSections = config.agent.sections.filter(section => !availableSections.includes(section))
  if (missingConfiguredSections.length > 0) {
    console.warn(chalk.yellow(`⚠ Configured sections not found: ${missingConfiguredSections.join(', ')}`))
  }

  // Filter to configured sections (or use all if not specified)
  const sectionsToInclude = config.agent.sections.length > 0
    ? config.agent.sections.filter(s => availableSections.includes(s))
    : availableSections

  const selectedSections = new Set(sectionsToInclude)
  const docs = discoveredDocs.filter(doc => selectedSections.has(doc.id))

  // Determine which files to generate
  const generateAll = !options.agentsMd && !options.llmsTxt && !options.docsJson && !options.installMd && !options.agentArtifacts
  const filesToGenerate = {
    agentsMd: generateAll || options.agentsMd,
    llmsTxt: generateAll || options.llmsTxt,
    docsJson: generateAll || options.docsJson,
    installMd: generateAll || options.installMd,
    agentArtifacts: generateAll || options.agentArtifacts,
  }

  const artifacts: GeneratedArtifact[] = []
  const selectedScopes: GenerationScope[] = []
  const agentArtifactBuild = filesToGenerate.agentArtifacts
    ? await buildAgentArtifactFiles({
        rootDir: cwd,
        docsDir: docsPath,
        project: {
          name: config.project.name,
          version: config.project.version,
          tagline: config.project.tagline,
        },
      })
    : undefined

  // Generate AGENTS.md
  if (filesToGenerate.agentsMd) {
    const content = generateAgentsMd(
      config.project.name,
      config.project.tagline,
      config,
      docs
    )
    artifacts.push({ path: 'AGENTS.md', content, marker: true, scope: 'agentsMd' })
    selectedScopes.push('agentsMd')
  }

  // Generate llms.txt
  if (filesToGenerate.llmsTxt) {
    const content = generateLlmsTxt(
      config.project.name,
      config.project.tagline,
      docs,
      agentArtifactBuild?.manifest,
    )
    artifacts.push({ path: 'llms.txt', content, marker: true, scope: 'llmsTxt' })
    selectedScopes.push('llmsTxt')
  }

  // Generate docs.json
  if (filesToGenerate.docsJson) {
    const content = generateDocsJson(
      config.project.name,
      config.project.version,
      config.project.tagline,
      docs
    )
    artifacts.push({ path: 'docs.json', content, scope: 'docsJson' })
    selectedScopes.push('docsJson')
  }

  // Generate install.md (installmd.org standard)
  if (filesToGenerate.installMd) {
    const content = generateInstallMd(config, docs)
    artifacts.push({ path: 'install.md', content, marker: true, scope: 'installMd' })
    selectedScopes.push('installMd')
  }

  let agentArtifactCounts: { docs: number; prompts: number } | undefined
  if (agentArtifactBuild) {
    artifacts.push(...agentArtifactBuild.files)
    selectedScopes.push('agentArtifacts')
    agentArtifactCounts = { docs: agentArtifactBuild.docs, prompts: agentArtifactBuild.prompts }
  }

  const plan = await planGeneratedArtifacts(outputPath, artifacts, selectedScopes, {
    overwrite: options.overwrite,
  })
  printGenerationPlan(plan.operations)

  if (!options.dryRun) await applyGenerationPlan(plan)

  const generatedSectionFiles = filesToGenerate.agentsMd || filesToGenerate.llmsTxt || filesToGenerate.docsJson || filesToGenerate.installMd

  console.log(chalk.blue(options.dryRun ? '\n🔎 Dry run complete; no files were written.\n' : '\n✨ Agent files generated!\n'))
  console.log(`Output directory: ${chalk.gray(outputPath)}`)
  if (generatedSectionFiles) {
    console.log(`Included sections: ${chalk.gray(sectionsToInclude.join(', '))}`)
  }
  if (agentArtifactCounts) {
    console.log(`Agent artifacts: ${chalk.gray(`${agentArtifactCounts.docs} docs, ${agentArtifactCounts.prompts} prompts`)}`)
  }
  console.log()

  return plan
}

function printGenerationPlan(operations: Array<{ action: GenerationAction; path: string; reason?: string }>): void {
  const labels: Record<GenerationAction, string> = {
    create: chalk.green('CREATE'),
    update: chalk.yellow('UPDATE'),
    delete: chalk.red('DELETE'),
    preserve: chalk.magenta('PRESERVE'),
    unchanged: chalk.gray('UNCHANGED'),
  }

  console.log(chalk.blue('Generation plan:'))
  for (const operation of operations) {
    const reason = operation.reason ? chalk.gray(` — ${operation.reason}`) : ''
    console.log(`  ${labels[operation.action].padEnd(17)} ${operation.path}${reason}`)
  }
  console.log()
}
